---
- name: Local VM | Mount network folders
  become: yes
  mount:
    name: "{{ mount_name }}/{{ item }}"
    src: "{{ mount_src }}/{{ item }}"
    fstype: cifs
    opts: "uid={{ uid }},gid={{ gid }},username={{ username }},password={{ password }},domain={{ domain }}"
    state: mounted
  with_items: "{{ mounted_dirs }}"
  when: mount_network_folders
  ignore_errors: yes

- name: Local VM | Create shared folder
  file: path="{{ shared_dir }}" state=directory
  when: shared_dir is defined

- name: Local VM | Ensure .ipython folder exists
  file: path=/home/vagrant/.ipython state=directory

- name: Local VM | Ensure .ipython/profile_default folder exists
  file: path=/home/vagrant/.ipython/profile_default state=directory

- name: Local VM | Check if ipython history file exists in default location
  stat: path=/home/vagrant/.ipython/profile_default/history.sqlite
  register: ipython_history

- name: Local VM | Move ipython history file if it exists in default location
  command: mv /home/vagrant/.ipython/profile_default/history.sqlite /vagrant/shared/history.sqlite
  when: ipython_history.stat.exists and not ipython_history.stat.islnk

- name: Local VM | Create link to ipython history file
  file: path=/home/vagrant/.ipython/profile_default/history.sqlite
        src=/vagrant/shared/ipython_history.sqlite
        state=link
        force=yes

- name: Local VM | Check if bash history file exists in default location
  stat: path=/home/vagrant/.bash_history
  register: bash_history

- name: Local VM | Move bash history file if it exists in default location
  command: mv /home/vagrant/.bash_history /vagrant/shared/dot_bash_history
  when: bash_history.stat.exists and not bash_history.stat.islnk

- name: Local VM | Create shared bash history file
  command: touch /vagrant/shared/dot_bash_history
  when: not bash_history.stat.exists

- name: Local VM | Create link to shared bash history file
  file: path=/home/vagrant/.bash_history
        src=/vagrant/shared/dot_bash_history
        state=link
        force=yes
