---
use_conda_cache: yes
nansat_version: v0.6.14
pythesint_version: v1.1.1

nansat_reqs:
    - qt
    - numpy
    - scipy
    - matplotlib
    - nose
    - basemap
    - basemap-data-hires
    - netcdf4
    - ipython
    - jupyter
    - gdal
    - pillow
    - cmocean
