---
# setup_python
conda_core_pkgs:
  - django=1.9
  - coverage
  - psycopg2
conda_xtra_pkgs: []
use_local_database: yes

# django_deploy
django_app_user: 'vagrant'
django_deploy_root_path: '{{ dev_sources_dir }}'
#django_project_name: '{{ django_project_name }}' # provided in vm group vars
django_project_path: '{{ django_deploy_root_path }}/{{ django_project_name }}'

geospaas_static_root: "{{ dev_sources_dir }}/site_media/static"
geospaas_media_root: "{{ dev_sources_dir }}/site_media/media/"
geospaas_downloads_root: "{{ dev_sources_dir }}/site_media/downloads"
geospaas_products_root: "{{ dev_sources_dir }}/site_media/products"

# django_extend
git_force: no

core_repos_apps:
  - {url: "https://github.com/nansencenter", repo: django-geo-spaas, app: geospaas, version: master}

geospaas_core_apps:
  - geospaas
  - geospaas.vocabularies
  - geospaas.catalog
  - geospaas.nansat_ingestor
  - geospaas.viewer
  - django_forms_bootstrap
  - leaflet

geospaas_core_urls:
  - "    url(r'^', include('geospaas.urls')),"
  - "    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)[0],"

xtra_repos_apps: []
geospaas_xtra_apps: []
geospaas_xtra_urls: []

# setup_db
make_migrations: yes
run_migrate: yes

# sample_data2db
add_sample_data: yes
private_sample_files: []
